            binary/Dockerfile:
              - 'binary/version'
            binary/builder/Dockerfile:
              - 'binary/builder/version'
            dotnet20/Dockerfile:
              - 'dotnet/version'
            python/Dockerfile:
              - 'python/version'
            python/Dockerfile-2.7:
              - 'python/version-2.7'              
            go/Dockerfile:
              - 'go/version'
            go/Dockerfile-1.11.4:
              - 'go/version-1.11.4'
            jvm/Dockerfile:
              - 'jvm/version'
            nodejs/Dockerfile:
              - 'nodejs/version'
            perl/Dockerfile:
              - 'perl/version'
            php7/Dockerfile:
              - 'php7/version'
            ruby/Dockerfile:
              - 'ruby/version'