binary-env-img:
  - 'binary/version'
binary-builder-img:
  - 'binary/builder/version'
dotnet-env-img:
  - 'dotnet/version'
dotnet20-env-img:
  - 'dotnet20/version'
dotnet20-builder-img:
  - 'dotnet20/builder/version'     
python-env-img:
  - 'python/version'
python-env-2.7-img:
  - 'python/version-2.7'              
go-env-img:
  - 'go/version'
go-env-1.12-img:
  - 'go/version-1.12'
go-env-1.13-img:
  - 'go/version-1.13'  
go-env-1.14-img:
  - 'go/version-1.14'
go-builder-img:
  - 'go/builder/version'
go-builder-1.11.4-img:
  - 'go/builder/version-1.11.4'  
go-builder-1.12-img:
  - 'go/builder/version-1.12'
go-builder-1.13-img:
  - 'go/builder/version-1.13'   
go-builder-1.14-img:
  - 'go/builder/version-1.14'    
jvm-env-img:
  - 'jvm/version'
jvm-builder-img:
  - 'jvm/builder/version'
jvm-jersey-env-img:
  - 'jvm-jersey/version'
jvm-jersey-env-11-img:
  - 'jvm-jersey/version-11'
jvm-jersey-builder-img:
  - 'jvm-jersey/version'
jvm-jersey-builder-11-img:
  - 'jvm-jersey/version-11'  
nodejs-env-img:
  - 'nodejs/version'
nodejs-env-12.16-img:
  - 'nodejs/version-12.16'
perl-env-img:
  - 'perl/version'
php7-env-img:
  - 'php7/version'
ruby-env-img:
  - 'ruby/version'
tensorflow-serving-env-img:
  - 'tensorflow-serving/version'  